### ISSUE TITLE
 How to use  isDisabled()  ?

### ISSUE THREAD

**Issue by Tokyo-Lei** [isaeken/plugin-system#1]
|- Plugin
    -- okclass.php
|- index.php

**okclass.php :**

`
class okclass extends \IsaEken\PluginSystem\Plugin
{
    public string $name = 'Plugin';

    public function hi()
    {
        return 'Hello world from: '.__CLASS__;
    }
    return okclass ::class;
}`

**index.php :**

`$pluginSystem = new IsaEken\PluginSystem\PluginSystem;

$pluginSystem->directory = 'Plugin';

$pluginSystem->autoload();

$success = $pluginSystem->execute('hi');

$pluginSystem->isDisabled('hi');???????
`

**How to judge that okclass is already in use ？**

**Comment by isaeken** [comment]
The disabled plugin names are `your_plugin.disabled.php`. If you need check the plugin is enabled or disabled, you can use this code:

```
foreach ($pluginSystem->plugins as $plugin) {
  if ($plugin->name == "your plugin" && $plugin->isEnabled()) {
    // ...
  }
}
```

or you can use this:

`
in_array($pluginSystem->enabledPlugins, $yourPlugin)
`
